# Generated by Django 5.0.1 on 2024-02-25 12:45

import operations.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, max_length=250, null=True, upload_to='sliderImage/', validators=[operations.utils.validateImage, operations.utils.validate_image_dimensions])),
            ],
        ),
    ]
