# Generated by Django 5.0.1 on 2024-02-28 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquries',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
