# Generated by Django 5.0.1 on 2024-02-27 08:31

import django.db.models.deletion
import operations.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default=None, max_length=250, null=True, upload_to='productImage/', validators=[operations.utils.validateImage, operations.utils.validate_Square_image])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categoryinfo')),
            ],
        ),
    ]
